dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: QJNptCAcZGG9gYAw0CxTZvsdQQQhpn8igSAkBFXFIkFqjeIwGygSWidDjHwYWmDX34LIij7MTDKk30HZ2MFyTxTAI3gU16CfKqL8iYR5y7KhkDG3tkhQR2BdH+BDg0MXqTcb1AZsys/eLM06ACmnxO4CjMjXzht3VRbmqW9zddQznESw9L67155ok4z1jap4pxWHO7diBHIZBTRPfdGNxbtMvX/cMCvB/XEUOhswl/O1JsssxzJxILbE8/TXGh+/3vhFh9AJHe1GhVS7iRenmbFSLL2sGLyuZEUbKF2QGKZI8XHrrA6AeFdWxqkmFOn66GvX0O3MMnlnlnsrriMWk+iAmROgfLrsPMLzIRUeI2hMtd3/Ld+r9Gfqr1/C7TGGDEmXGdXjYQB0eK5c5sFaH2n0Yjxs6jpLcW1Alo4p2svfd4a4JMH2FIIYD1oh5N0qtWHoePvO8S6mrDBjscOunFgF3nYGKsKIa6H5Bprze5kKnnxd5pJa+uTIlKLg5Z6bvYtjonFJ+VthexumdaG6b6kip0q0rGQkhUpX2vQdTdHTe/+ryQ+sEvzmZg1L345cyrdcp4hl7nceM1cabgkhEHyKXmNeIC9ntmZ8GJeNsthn3qDCGRxnZMhp5UPNKnlX1+LwXuzATIADmlBOrkaTAjh1GexJaH6ZhifnxCBHJ0g=
